### ISSUE TITLE
Create drawer

### ISSUE THREAD

**Issue by Right2Drive** [agriculture-capstone/agritrader#15]
## Description
**Android navigation drawer accessible from most pages in the application**

## Acceptance Criteria
- Can swipe from left side to access drawer
- Can add routes to drawer via props
- Drawer matches UX

## Reviewer
Brad

## QA
Moath

**Comment by nscassar** [comment]
Just a quick note: The drawer width is currently hard-coded to pull open and cover a certain amount of the screen. We should try and find a way to calculate the screen size on a device-specific basis to have consistent drawer UX across all devices
