### ISSUE TITLE
put git branch name in jenkin builds

### ISSUE THREAD

**Issue by beaesguerra** [agriculture-capstone/agritrader#34]
## Reviewer

Brad

**Comment by enochtsang** [comment]
Done, installed jenkins plugin `build-name-setter`. 

To configure, went to a project in jenkins, configure, build environment. Check off `Set Build Name` and used `#${BUILD_NUMBER}:${GIT_BRANCH}`

**Comment by beaesguerra** [comment]
Reviewed! Looks good!

**Comment by beaesguerra** [comment]
does this need to be QA'd still? or can this be moved to done?

**Comment by enochtsang** [comment]
Can be done
