### ISSUE TITLE
[BUILD BREAK] - Gradle

### ISSUE THREAD

**Issue by Right2Drive** [agriculture-capstone/agritrader#71]
Issue with `Merge pull request #41 from agriculture-capstone/enochtsang/at-20/bui…`

```
[React-Native] FAILURE: Build failed with an exception.
[React-Native]
[React-Native] * Where:
[React-Native] Build file '<project_dir>/agritrader/android/app/build.gradle' line: 112
[React-Native]
[React-Native] * What went wrong:
A problem occurred evaluating project ':app'.
[React-Native] > Could not get unknown property 'AGRITRADER_DEPLOY_UNSTABLE_STORE_FILE' for SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.
[React-Native]
[React-Native] * Try:
[React-Native] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[React-Native]
[React-Native] BUILD FAILED
[React-Native]
[React-Native] Total time: 4.882 secs
[React-Native] Could not install the app on the device, read the error above for details.
```

**Comment by Right2Drive** [comment]
@enochtsang I think this is due to your merge

**Comment by enochtsang** [comment]
@jeinglis rand I were looking at this yesterday. It seemed like Bea never had any issues so we thought it was a windows only problem. @jeinglis posted a workaround in a board but I don't know how to get to the boards to link to it. 

That particular variable `AGRITRADER_DEPLOY_UNSTABLE_STORE_FILE` is supposed to be in `gradle.properties`. I thought it would only be necessary when building APKs but I guess it affects dev builds as well. @beaesguerra @Right2Drive do you guys have any idea how to get the build to read gradle.properties in dev builds?
