### ISSUE TITLE
Clean up Muaz's changes

### ISSUE THREAD

**Issue by Right2Drive** [agriculture-capstone/agritrader#84]
## Acceptance Criteria

- Clean up:
  - `/src/view/pages/Farmer/tabs/Info`

## Reviewers
- James
- Brad

**Comment by mfalthaw** [comment]
Hey @Right2Drive , what about my pages?
  - `/src/view/pages/Farmer/tabs/FarmerInformation/*`

**Comment by Right2Drive** [comment]
@mfalthaw I wrote in the description /tabs/Info because it should probably be named to match the other tabs

**Comment by Right2Drive** [comment]
I was under the impression you wrote the other two pages, Bea will be doing her own pages and you are only responsible for Info.

**Comment by mfalthaw** [comment]
@Right2Drive I did 
  - `*/FarmerInformation/addFarmer`
  - `*/FarmerInformation/editFarmer`
  - `*/FarmerInformation/viewFarmer`
